### ISSUE TITLE
Please add PSM+ Publisher License Generation code.

### ISSUE THREAD

**Issue by LiEnby** [yifanlu/PSMSigner#2]
id like to not have to rely on a server, being up. especially since the one on wololo.net is broken.

having the src code would mean i dont have to deal with email tricks either
if you dont wanna upload src could we atleast get binarys?

**Comment by yifanlu** [comment]
Literally the code is this repo.

**Comment by LiEnby** [comment]
no, this only appears to be the code relating to the "refresh license" part but not for the "generate publisher license" part of PSM+ (this thing: https://hackinformer.com/psmplus/ui/psmdev_new.html)

theres also nothing here for the Unity Developer application ..

**Comment by yifanlu** [comment]
You'll have to ask the owner of that site. I did not write that.

**Comment by LiEnby** [comment]
okay i guess..
